"""
services/image_service.py
--------------------------
Local image storage for work_log_entries.

Directory layout:
  <app_dir>/field_images/<work_log_id>/<image_id>.jpg
  <app_dir>/field_images/<work_log_id>/<image_id>_thumb.jpg

Notes:
  - Requires Pillow for thumbnail generation and EXIF reading.
    If Pillow is unavailable, images are stored without thumbnails.
  - sha256 is computed after copy for integrity.
  - File sizes are capped at 25 MB; MIME is validated by magic bytes.

Short video from the phone lives here too, as a `work_log_images` row whose
`mime_type` is a video one. Nothing about the storage, the hashing, the export
or the retention sweep needs to know the difference — only the thumbnail does.
There is no ffmpeg here and there must not be, so a clip's "thumbnail" is the
poster frame the phone grabbed at capture and uploaded with it, fetched from
the server by `download_remote_image` instead of being generated by Pillow.
"""

import hashlib
import os
import shutil
import sys
import uuid
from datetime import datetime
from typing import Optional, List

from database.db_manager import DB_PATH, get_connection

# ── Allowed image types (magic bytes) ────────────────────────────────────────

_MAGIC = {
    b'\xff\xd8\xff': 'image/jpeg',
    b'\x89PNG':      'image/png',
    b'RIFF':         'image/webp',   # partial; webp has RIFF header
    b'\x00\x00\x00': 'image/heic',  # approximate; will be verified by PIL
}

# What a phone's MediaRecorder writes: WebM (VP8/VP9 + Opus) on Android Chrome,
# MP4 (H.264 + AAC) where that is offered, QuickTime from an iOS capture.
VIDEO_MIMES = {'video/webm', 'video/mp4', 'video/quicktime'}
_VIDEO_EXTS = {'.webm', '.mp4', '.m4v', '.mov', '.mkv'}

MAX_FILE_BYTES = 25 * 1024 * 1024   # 25 MB
# A clip has its own cap, as it does on the server: the phone records at most
# 30 s at roughly 0.7 Mbit/s, so ~3 MB, and 40 MB is headroom rather than a
# licence. Separate from MAX_FILE_BYTES on purpose.
MAX_VIDEO_BYTES = 40 * 1024 * 1024
THUMB_SIZE     = (320, 240)


def is_video(row) -> bool:
    """Is this work_log_images row a clip rather than a photo?

    The mime type decides. The file name is the fallback and only the fallback:
    rows written before this column existed have no mime_type, and a clip that
    reached such a row (there are none, but a hand-edited database is a thing)
    should still read as a clip rather than as a photo that will not open.
    """
    if row is None:
        return False

    def get(key):
        # dict, sqlite3.Row, or anything else that indexes: a sqlite3.Row has
        # no .get() and raises for a column the query did not select, so ask
        # for nothing without a guard.
        try:
            return row[key]
        except (KeyError, IndexError, TypeError):
            return None

    mime = get('mime_type') or ''
    if mime:
        return str(mime).split(';')[0].strip().lower() in VIDEO_MIMES
    name = (get('filename') or '') or (get('file_path') or '')
    return os.path.splitext(str(name))[1].lower() in _VIDEO_EXTS


def duration_text(ms) -> str:
    """'0:07' — a clip's length as a person reads it."""
    try:
        total = int(round(float(ms or 0) / 1000.0))
    except (TypeError, ValueError):
        return ''
    if total <= 0:
        return ''
    return '{}:{:02d}'.format(total // 60, total % 60)


# ── Paths ─────────────────────────────────────────────────────────────────────

def _get_field_images_dir() -> str:
    # The photos belong beside the database, not beside the exe: when the exe's
    # own folder cannot be written to, db_manager puts the database in
    # %LOCALAPPDATA%\BESS Tracker, and photos that stayed next to the exe would
    # fail to save while everything else worked. For any writable installation
    # the two folders are the same one, so nothing moves.
    if getattr(sys, 'frozen', False):
        base_dir = os.path.dirname(DB_PATH)
    else:
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    d = os.path.join(base_dir, 'field_images')
    os.makedirs(d, exist_ok=True)
    return d


def get_image_dir(work_log_id: str) -> str:
    d = os.path.join(_get_field_images_dir(), work_log_id)
    os.makedirs(d, exist_ok=True)
    return d


# ── Helpers ───────────────────────────────────────────────────────────────────

def _compute_sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def _detect_mime(path: str) -> str:
    """Detect MIME type by magic bytes.

    Video is checked first and explicitly. The fallback for everything
    unrecognised stays 'image/jpeg' as it always was — the phones upload
    formats this does not match byte for byte and they must keep working — but
    a clip must never fall through it, or it would be filed as a photo and
    Pillow would be asked to open it.
    """
    try:
        with open(path, 'rb') as f:
            header = f.read(16)
    except Exception:
        return 'image/jpeg'
    if header[:4] == b'\x1a\x45\xdf\xa3':
        return 'video/webm'                       # EBML: Matroska / WebM
    if header[4:8] == b'ftyp':
        # MP4, QuickTime and HEIC all say "ftyp"; the brand after it decides.
        brand = header[8:12]
        if brand == b'qt  ':
            return 'video/quicktime'
        if brand in (b'heic', b'heix', b'heim', b'heis', b'hevc', b'hevx',
                     b'mif1', b'msf1'):
            return 'image/heic'
        return 'video/mp4'
    for magic, mime in _MAGIC.items():
        if header.startswith(magic):
            return mime
    return 'image/jpeg'   # fallback


def _generate_thumbnail(src: str, dst: str) -> bool:
    """Generate a THUMB_SIZE JPEG thumbnail.  Returns True on success."""
    try:
        from PIL import Image
        with Image.open(src) as img:
            img = img.convert('RGB')
            img.thumbnail(THUMB_SIZE, Image.LANCZOS)
            img.save(dst, 'JPEG', quality=75, optimize=True)
        return True
    except Exception:
        return False


def _get_exif_taken_at(path: str) -> Optional[str]:
    """Return ISO 8601 string from EXIF DateTimeOriginal, or None."""
    try:
        from PIL import Image
        from PIL.ExifTags import TAGS
        with Image.open(path) as img:
            exif = img._getexif()
            if exif:
                for tag_id, value in exif.items():
                    if TAGS.get(tag_id) == 'DateTimeOriginal':
                        # "2024:03:15 14:30:00" → "2024-03-15T14:30:00"
                        return value[:10].replace(':', '-') + 'T' + value[11:]
    except Exception:
        pass
    return None


def _get_dimensions(path: str):
    """Return (width, height) or (None, None)."""
    try:
        from PIL import Image
        with Image.open(path) as img:
            return img.size
    except Exception:
        return (None, None)


def _now() -> str:
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S')


# ── Public API ────────────────────────────────────────────────────────────────

def save_image(work_log_id: str, source_path: str) -> Optional[dict]:
    """
    Copy *source_path* into app image storage, generate thumbnail,
    compute SHA-256, and insert a work_log_images row.

    Returns the full image record dict, or None on failure.
    """
    if not os.path.isfile(source_path):
        return None

    size_bytes = os.path.getsize(source_path)
    mime_type  = _detect_mime(source_path)
    video      = mime_type in VIDEO_MIMES
    cap        = MAX_VIDEO_BYTES if video else MAX_FILE_BYTES
    if size_bytes > cap:
        raise ValueError(
            "{} too large ({} MB). Max is {} MB.".format(
                'Clip' if video else 'Image',
                size_bytes // (1024 * 1024), cap // (1024 * 1024))
        )

    log_dir   = get_image_dir(work_log_id)
    image_id  = str(uuid.uuid4())
    ext       = os.path.splitext(source_path)[1].lower() or '.jpg'
    dest_path = os.path.join(log_dir, f"{image_id}{ext}")
    thumb_path = os.path.join(log_dir, f"{image_id}_thumb.jpg")

    shutil.copy2(source_path, dest_path)

    sha256    = _compute_sha256(dest_path)
    # Pillow cannot open a clip: no EXIF, no dimensions, no thumbnail from it.
    # A clip attached on the desktop therefore has no poster (only the phone,
    # which held the camera, can make one) and shows as a clip without a still.
    taken_at  = None if video else _get_exif_taken_at(dest_path)
    width, height = (None, None) if video else _get_dimensions(dest_path)

    has_thumb = False if video else _generate_thumbnail(dest_path, thumb_path)
    if not has_thumb:
        thumb_path = None

    filename  = os.path.basename(source_path)
    now       = _now()

    conn = get_connection()
    try:
        conn.execute("""
            INSERT INTO work_log_images
                (id, work_log_id, file_path, thumbnail_path,
                 filename, size_bytes, sha256, width, height,
                 taken_at, uploaded_at, upload_status, mime_type)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'local', ?)
        """, (image_id, work_log_id, dest_path, thumb_path,
              filename, size_bytes, sha256, width, height,
              taken_at, now, mime_type))
        conn.commit()
    finally:
        conn.close()

    return {
        'id':             image_id,
        'work_log_id':    work_log_id,
        'file_path':      dest_path,
        'thumbnail_path': thumb_path,
        'filename':       filename,
        'size_bytes':     size_bytes,
        'sha256':         sha256,
        'mime_type':      mime_type,
        'width':          width,
        'height':         height,
        'taken_at':       taken_at,
        'uploaded_at':    now,
        'upload_status':  'local',
    }


def get_images_for_log(work_log_id: str) -> List[dict]:
    """Return all images for a given work_log_entry, ordered by upload time."""
    conn = get_connection()
    try:
        rows = conn.execute("""
            SELECT * FROM work_log_images
            WHERE work_log_id = ?
            ORDER BY uploaded_at ASC
        """, (work_log_id,)).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def delete_image(image_id: str):
    """Delete image + thumbnail files and remove the DB row."""
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT file_path, thumbnail_path FROM work_log_images WHERE id=?",
            (image_id,)
        ).fetchone()
        if row:
            for path in [row['file_path'], row['thumbnail_path']]:
                if path and os.path.isfile(path):
                    try:
                        os.remove(path)
                    except OSError:
                        pass
        conn.execute("DELETE FROM work_log_images WHERE id=?", (image_id,))
        conn.commit()
    finally:
        conn.close()


def download_remote_image(image_id: str, work_log_id: str) -> Optional[str]:
    """
    Return the local file path for *image_id*.
    If the file doesn't exist locally (upload_status='remote'), attempt to
    download it from the sync server, get it a thumbnail, and update the DB.
    Returns the local path on success, None on failure.

    "Get it a thumbnail" differs by kind: a photo's is generated here with
    Pillow, a clip's is the poster frame the phone recorded and is fetched from
    the server, because nothing on either side can make one from a video.
    """
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT * FROM work_log_images WHERE id=?", (image_id,)
        ).fetchone()
        if not row:
            return None
        row = dict(row)
    finally:
        conn.close()

    # Already available locally. A clip may still be missing its poster — the
    # file arrived, the poster fetch failed — so top that up before returning:
    # this is the retry path, and the sweep will not confirm a clip whose
    # poster it was told about and does not have.
    fp = row.get("file_path", "")
    if fp and os.path.isfile(fp):
        if is_video(row) and not (row.get("thumbnail_path") or ''):
            if ensure_poster(row) and row.get("upload_status") == 'remote':
                # The clip was already here, only its poster was missing: with
                # both in hand the row is finally held by this desktop, which
                # is what lets the sweep offer it to the server.
                conn = get_connection()
                try:
                    conn.execute("UPDATE work_log_images SET upload_status='uploaded' "
                                 "WHERE id=? AND upload_status='remote'", (image_id,))
                    conn.commit()
                finally:
                    conn.close()
        return fp

    # Try to download from server
    try:
        from services.sync_client import download_image_file
        log_dir  = get_image_dir(work_log_id)
        filename = row.get("filename") or f"{image_id}.jpg"
        dest     = os.path.join(log_dir, filename)
        # Phones name every photo "image.jpg", so two photos on one record used
        # to land on the same path and the second overwrote the first: one row
        # then pointed at another photo's file, and the only good copy of the
        # loser was the server's. Same convention as the readable photo folders.
        if os.path.exists(dest):
            stem, ext = os.path.splitext(filename)
            dest = os.path.join(log_dir, f"{stem}_{image_id[:8]}{ext or '.jpg'}")

        if download_image_file(image_id, dest):
            thumb = os.path.join(log_dir, f"{image_id}_thumb.jpg")
            video = is_video(dict(row, file_path=dest))
            if video:
                # No ffmpeg here: the only still a clip can have is the poster
                # the phone recorded, so it is fetched, not generated.
                has_thumb = _fetch_poster(image_id, thumb)
            else:
                has_thumb = _generate_thumbnail(dest, thumb)

            # A clip whose poster did not arrive stays 'remote', so the next
            # sync tries the poster again — and because the retention sweep
            # only ever offers 'uploaded' rows, the server can never be told to
            # delete a poster this desktop has not got.
            #
            # file_path is written EITHER WAY. Leaving it empty on a failed
            # poster fetch would make the next sync download the clip again,
            # to a fresh non-colliding name each time, and a phone in a bad
            # signal area would leave a copy of the clip per sync on disk.
            done = 'uploaded' if (has_thumb or not video) else 'remote'
            conn = get_connection()
            try:
                conn.execute(
                    """UPDATE work_log_images
                          SET file_path=?, thumbnail_path=?, upload_status=?,
                              mime_type=COALESCE(mime_type, ?)
                        WHERE id=?""",
                    (dest, thumb if has_thumb else None, done,
                     _detect_mime(dest), image_id),
                )
                conn.commit()
            finally:
                conn.close()
            return dest
    except Exception:
        pass
    return None


def _fetch_poster(image_id: str, dest: str) -> bool:
    """Download a clip's poster frame from the server. False on any failure."""
    try:
        from services.sync_client import download_image_poster
    except Exception:                                        # noqa: BLE001
        return False
    try:
        if not download_image_poster(image_id, dest):
            return False
    except Exception:                                        # noqa: BLE001
        return False
    return os.path.isfile(dest)


def ensure_poster(row: dict) -> bool:
    """Make sure a clip's poster is on this computer, fetching it if not.

    Separate from the download above because the two can fail apart: a clip can
    arrive in one sync and its poster in the next. Returns True when the row now
    has a poster file.
    """
    if not is_video(row):
        return False
    have = row.get('thumbnail_path') or ''
    if have and os.path.isfile(have):
        return True
    dest = os.path.join(get_image_dir(row['work_log_id']),
                        "{}_thumb.jpg".format(row['id']))
    if not _fetch_poster(row['id'], dest):
        return False
    conn = get_connection()
    try:
        conn.execute("UPDATE work_log_images SET thumbnail_path=? WHERE id=?",
                     (dest, row['id']))
        conn.commit()
    finally:
        conn.close()
    row['thumbnail_path'] = dest
    return True


def delete_images_for_log(work_log_id: str):
    """Delete all images belonging to a log entry (used during full entry delete)."""
    images = get_images_for_log(work_log_id)
    for img in images:
        delete_image(img['id'])


# ── Export photos to the user's computer ──────────────────────────────────────

def _safe_name(s: str, maxlen: int = 60) -> str:
    """Make a string safe to use as a file/folder name."""
    import re
    s = re.sub(r'[^\w\-. ]+', '_', (s or '')).strip().strip('.')
    s = re.sub(r'\s+', '_', s)
    return s[:maxlen] or 'photo'


def export_entry_images(work_log_id: str, dest_dir: str,
                        name_prefix: str = "") -> dict:
    """
    Copy every photo of an entry into *dest_dir* (creating it if needed).
    Remote-only photos are downloaded from the sync server first.

    name_prefix : if given, files are named '<prefix>_01.jpg', '<prefix>_02.jpg' …;
                  otherwise the original filename is kept (sanitised).

    Returns {'saved': int, 'failed': [str], 'total': int, 'dest': str,
             'videos': int}.

    Video clips come out with the photos, under their own extension: they are
    rows of the same table, and a record's evidence is not two exports.
    """
    os.makedirs(dest_dir, exist_ok=True)
    images = get_images_for_log(work_log_id)
    saved, failed, videos = 0, [], 0

    for i, img in enumerate(images, 1):
        src = img.get('file_path') or ''
        if not (src and os.path.isfile(src)):
            src = download_remote_image(img['id'], work_log_id) or ''
        if not (src and os.path.isfile(src)):
            failed.append(img.get('filename') or img['id'])
            continue

        orig = img.get('filename') or os.path.basename(src)
        ext = os.path.splitext(orig)[1] or '.jpg'
        if name_prefix:
            base = f"{_safe_name(name_prefix)}_{i:02d}"
        else:
            base = _safe_name(os.path.splitext(orig)[0] or f"photo_{i}")

        dest = os.path.join(dest_dir, base + ext)
        k = 1
        while os.path.exists(dest):
            dest = os.path.join(dest_dir, f"{base}_{k}{ext}")
            k += 1
        try:
            shutil.copy2(src, dest)
            saved += 1
            if is_video(img):
                videos += 1
        except Exception as ex:
            failed.append(f"{orig}: {ex}")

    return {'saved': saved, 'failed': failed, 'total': len(images),
            'dest': dest_dir, 'videos': videos}
