"""
models/schemas.py
------------------
Pydantic request / response schemas.
"""

from __future__ import annotations

from typing import Optional, List, Any
from pydantic import BaseModel, Field


# ── Auth ──────────────────────────────────────────────────────────────────────

class LoginRequest(BaseModel):
    username:  str
    password:  str
    device_id: Optional[str] = None


class RefreshRequest(BaseModel):
    refresh_token: str
    device_id:     Optional[str] = None


class UserOut(BaseModel):
    id:         str
    username:   str
    email:      Optional[str]
    role:       str
    created_at: str

    model_config = {"from_attributes": True}


class AssignableUser(BaseModel):
    """Who the office may give a job to — the name and nothing else. The
    desktop caches these so its "Assigned to" picker works offline."""
    id:       str
    username: str
    role:     str = ""

    model_config = {"from_attributes": True}


class TokenResponse(BaseModel):
    access_token:  str
    refresh_token: str
    token_type:    str = "bearer"
    user:          UserOut


class AccessTokenResponse(BaseModel):
    access_token:  str
    refresh_token: str          # new rotated refresh token
    token_type:    str = "bearer"


# ── Work log entries ──────────────────────────────────────────────────────────

class WorkLogEntryCreate(BaseModel):
    id:               str                    # UUID generated by client
    project_id:       int
    container_id:     Optional[int]   = None
    equipment_serial: str             = ""
    site_location:    str             = ""
    category:         str             = "maintenance"
    description:      str
    log_date:         str                    # YYYY-MM-DD
    created_at:       str
    updated_at:       str
    version:          int             = 1
    origin_device:    Optional[str]   = None
    tags:             List[str]       = Field(default_factory=list)


class WorkLogEntryUpdate(BaseModel):
    category:         Optional[str]   = None
    description:      Optional[str]   = None
    equipment_serial: Optional[str]   = None
    site_location:    Optional[str]   = None
    log_date:         Optional[str]   = None
    tags:             Optional[List[str]] = None


class WorkLogImageOut(BaseModel):
    id:             str
    work_log_id:    str
    filename:       str
    size_bytes:     int
    width:          Optional[int]
    height:         Optional[int]
    taken_at:       Optional[str]
    uploaded_at:    str
    updated_at:     str
    download_url:   str              # injected by router

    model_config = {"from_attributes": True}


class WorkLogEntryOut(BaseModel):
    id:               str
    user_id:          str
    # Optional: phone entries carry no project, and a required int made
    # GET /worklogs/{id} answer 500 for every one of them.
    project_id:       Optional[int] = None
    container_id:     Optional[int]
    equipment_serial: str
    site_location:    str
    category:         str
    description:      str
    log_date:         str
    created_at:       str
    updated_at:       str
    deleted_at:       Optional[str]
    version:          int
    origin_device:    Optional[str]
    tags:             List[str]      = Field(default_factory=list)
    images:           List[WorkLogImageOut] = Field(default_factory=list)

    model_config = {"from_attributes": True}


# ── Projects ──────────────────────────────────────────────────────────────────

class ProjectOut(BaseModel):
    id:           int
    name:         str
    project_type: str = "BESS"
    num_blocks:   int = 0
    # Zones as the plant really numbers them: [[zone, first block, last
    # block], ...]. The phone's node picker shows a zone grid with the
    # plant block numbers on it; without the real map it would have to
    # guess where a zone starts, and a guessed "Z4/B8" is worse than none.
    # Empty for an older desktop.
    zones:        str = ""


class ProjectsSyncRequest(BaseModel):
    projects: List[ProjectOut]


# ── Stock (spare parts) ─────────────────────────────────────────────────────

class StockItemOut(BaseModel):
    project_id:      int
    material_number: str
    description:     str   = ""
    quantity:        float = 0
    unit:            str   = ""
    min_quantity:    float = 0


class StockSyncRequest(BaseModel):
    items: List[StockItemOut]


class WriteoffCreate(BaseModel):
    id:              str                     # UUID generated by client
    project_id:      int
    material_number: str
    description:     str = ""
    quantity:        float
    block:           str = ""
    note:            str = ""
    log_date:        str                     # YYYY-MM-DD
    created_at:      Optional[str] = None


class WriteoffOut(BaseModel):
    id:              str
    project_id:      int
    material_number: str
    description:     str
    quantity:        float
    block:           str
    note:            str
    log_date:        str
    created_at:      str
    updated_at:      str

    model_config = {"from_attributes": True}


class WriteoffPullResponse(BaseModel):
    writeoffs: List[WriteoffOut]
    cursor:    str
    has_more:  bool


# ── Field events (PM / downtime / exclusion) ─────────────────────────────────

class FieldEventCreate(BaseModel):
    id:             str
    project_id:     int
    kind:           str                      # pm | counts | excluded
    blocks:         str = ""
    date_from:      str
    date_to:        str
    hours:          float = 0
    exclusion_type: str = ""
    description:    str = ""
    created_at:     Optional[str] = None


class FieldEventOut(BaseModel):
    id:             str
    project_id:     int
    kind:           str
    blocks:         str
    date_from:      str
    date_to:        str
    hours:          float
    exclusion_type: str
    description:    str
    created_at:     str
    updated_at:     str

    model_config = {"from_attributes": True}


class FieldEventPullResponse(BaseModel):
    events:   List[FieldEventOut]
    cursor:   str
    has_more: bool


# ── PM checklists ───────────────────────────────────────────────────────────

class ChecklistTemplateOut(BaseModel):
    uuid:       str
    project_id: Optional[int] = None
    name:       str = ""
    kind:       str = ""
    # The items as the desktop numbered them: [{item_id, s_no, equipment,
    # activity, text, added}]. They travel with the template so the phone can
    # show a checklist it has not seen since its last sync.
    items:      List[dict[str, Any]] = Field(default_factory=list)
    updated_at: str = ""


class ChecklistTemplatesSyncRequest(BaseModel):
    templates: List[ChecklistTemplateOut]


class ChecklistRunOut(BaseModel):
    uuid:          str
    project_id:    int
    template_uuid: str
    plant_block:   Optional[int] = None
    campaign:      str = ""
    run_date:      str = ""
    status:        str = "In Progress"
    results:       dict[str, Any] = Field(default_factory=dict)
    ptw_no:        str = ""
    serial:        str = ""
    notes:         str = ""
    filled_by:     str = ""
    updated_at:    str = ""
    deleted_at:    Optional[str] = None


class ChecklistRunsSyncRequest(BaseModel):
    runs: List[ChecklistRunOut]


class ChecklistAssignedResponse(BaseModel):
    templates: List[ChecklistTemplateOut]
    runs:      List[ChecklistRunOut]
    # Paged by run uuid: the phone asks again with ?after=<cursor> while
    # has_more is true. A site with three checklists on each of 70 blocks is
    # more than one page, and a truncated list used to be silent.
    cursor:    str  = ""
    has_more:  bool = False


class ChecklistResultsIn(BaseModel):
    """What a phone sends back. Only the items it carries are touched, so a
    half-filled checklist never blanks the rest."""
    results:    dict[str, Any] = Field(default_factory=dict)
    status:     Optional[str] = None
    ptw_no:     Optional[str] = None
    serial:     Optional[str] = None
    filled_by:  Optional[str] = None
    notes:      Optional[str] = None
    updated_at: Optional[str] = None


class ChecklistRunPullResponse(BaseModel):
    runs:        List[ChecklistRunOut]
    cursor:      str
    # the second half of the cursor — a whole publish shares one timestamp
    cursor_uuid: str = ""
    has_more:    bool


# ── Action list ─────────────────────────────────────────────────────────────

class ActionItemOut(BaseModel):
    uuid:          str
    project_id:    int
    seq:           Optional[int] = None
    topic:         str = ""
    description:   str = ""
    todo:          str = ""
    due_date:      str = ""
    assigned_to:   str = ""
    assigned_name: str = ""
    status:        str = "open"
    done_at:       str = ""
    done_note:     str = ""
    done_by:       str = ""
    updated_at:    str = ""
    deleted_at:    Optional[str] = None


class ActionItemsSyncRequest(BaseModel):
    items: List[ActionItemOut]


class ActionItemsAssignedResponse(BaseModel):
    items:    List[ActionItemOut]
    # Paged by uuid, like the checklists: the phone asks again with
    # ?after=<cursor> while has_more is true.
    cursor:   str  = ""
    has_more: bool = False


class ActionItemDoneIn(BaseModel):
    """What a phone sends back when it finishes an item. Only the completion
    travels: the topic, the due date and the assignment are the office's."""
    status:     Optional[str] = None          # done | in progress
    done_note:  Optional[str] = None
    done_by:    Optional[str] = None
    done_at:    Optional[str] = None
    updated_at: Optional[str] = None


class ActionItemPullResponse(BaseModel):
    items:       List[ActionItemOut]
    cursor:      str
    # the second half of the cursor — a whole publish shares one timestamp
    cursor_uuid: str = ""
    has_more:    bool


# ── Sync ──────────────────────────────────────────────────────────────────────

class SyncChange(BaseModel):
    entity:  str                     # "work_log" | "work_log_image"
    id:      str
    action:  str                     # "upsert" | "delete"
    version: int
    payload: dict[str, Any]


class SyncPushRequest(BaseModel):
    device_id:       str
    changes:         List[SyncChange]
    idempotency_key: Optional[str] = None   # UUID; enables safe retry without false conflicts


class SyncChangeResult(BaseModel):
    id:             str
    outcome:        str                  # "applied" | "conflict" | "skipped" | "error"
    server_version: Optional[int]  = None  # new version after apply
    server_row:     Optional[dict] = None  # full server row on conflict (for UI merge)
    message:        Optional[str]  = None


class SyncPushResponse(BaseModel):
    results: List[SyncChangeResult]


class SyncPullChange(BaseModel):
    entity:     str
    action:     str                  # "upsert" | "delete"
    id:         str
    data:       dict[str, Any]
    updated_at: str


class SyncPullResponse(BaseModel):
    changes:  List[SyncPullChange]
    cursor:   str                    # ISO datetime — pass as `since` on next call
    has_more: bool


# ── Image upload ──────────────────────────────────────────────────────────────

class ImageUploadResponse(BaseModel):
    id:             str
    work_log_id:    str
    filename:       str
    size_bytes:     int
    sha256:         str
    width:          Optional[int]
    height:         Optional[int]
    taken_at:       Optional[str]
    uploaded_at:    str
    download_url:   str
