"""
models/schemas.py
------------------
Pydantic request / response schemas.
"""

from __future__ import annotations

from typing import Optional, List, Any
from pydantic import BaseModel, Field


# ── Auth ──────────────────────────────────────────────────────────────────────

class LoginRequest(BaseModel):
    username:  str
    password:  str
    device_id: Optional[str] = None


class RefreshRequest(BaseModel):
    refresh_token: str
    device_id:     Optional[str] = None


class UserOut(BaseModel):
    id:         str
    username:   str
    email:      Optional[str]
    role:       str
    created_at: str

    model_config = {"from_attributes": True}


class TokenResponse(BaseModel):
    access_token:  str
    refresh_token: str
    token_type:    str = "bearer"
    user:          UserOut


class AccessTokenResponse(BaseModel):
    access_token:  str
    refresh_token: str          # new rotated refresh token
    token_type:    str = "bearer"


# ── Work log entries ──────────────────────────────────────────────────────────

class WorkLogEntryCreate(BaseModel):
    id:               str                    # UUID generated by client
    project_id:       int
    container_id:     Optional[int]   = None
    equipment_serial: str             = ""
    site_location:    str             = ""
    category:         str             = "maintenance"
    description:      str
    log_date:         str                    # YYYY-MM-DD
    created_at:       str
    updated_at:       str
    version:          int             = 1
    origin_device:    Optional[str]   = None
    tags:             List[str]       = Field(default_factory=list)


class WorkLogEntryUpdate(BaseModel):
    category:         Optional[str]   = None
    description:      Optional[str]   = None
    equipment_serial: Optional[str]   = None
    site_location:    Optional[str]   = None
    log_date:         Optional[str]   = None
    tags:             Optional[List[str]] = None


class WorkLogImageOut(BaseModel):
    id:             str
    work_log_id:    str
    filename:       str
    size_bytes:     int
    width:          Optional[int]
    height:         Optional[int]
    taken_at:       Optional[str]
    uploaded_at:    str
    updated_at:     str
    download_url:   str              # injected by router

    model_config = {"from_attributes": True}


class WorkLogEntryOut(BaseModel):
    id:               str
    user_id:          str
    # Optional: phone entries carry no project, and a required int made
    # GET /worklogs/{id} answer 500 for every one of them.
    project_id:       Optional[int] = None
    container_id:     Optional[int]
    equipment_serial: str
    site_location:    str
    category:         str
    description:      str
    log_date:         str
    created_at:       str
    updated_at:       str
    deleted_at:       Optional[str]
    version:          int
    origin_device:    Optional[str]
    tags:             List[str]      = Field(default_factory=list)
    images:           List[WorkLogImageOut] = Field(default_factory=list)

    model_config = {"from_attributes": True}


# ── Projects ──────────────────────────────────────────────────────────────────

class ProjectOut(BaseModel):
    id:           int
    name:         str
    project_type: str = "BESS"
    num_blocks:   int = 0


class ProjectsSyncRequest(BaseModel):
    projects: List[ProjectOut]


# ── Stock (spare parts) ─────────────────────────────────────────────────────

class StockItemOut(BaseModel):
    project_id:      int
    material_number: str
    description:     str   = ""
    quantity:        float = 0
    unit:            str   = ""
    min_quantity:    float = 0


class StockSyncRequest(BaseModel):
    items: List[StockItemOut]


class WriteoffCreate(BaseModel):
    id:              str                     # UUID generated by client
    project_id:      int
    material_number: str
    description:     str = ""
    quantity:        float
    block:           str = ""
    note:            str = ""
    log_date:        str                     # YYYY-MM-DD
    created_at:      Optional[str] = None


class WriteoffOut(BaseModel):
    id:              str
    project_id:      int
    material_number: str
    description:     str
    quantity:        float
    block:           str
    note:            str
    log_date:        str
    created_at:      str
    updated_at:      str

    model_config = {"from_attributes": True}


class WriteoffPullResponse(BaseModel):
    writeoffs: List[WriteoffOut]
    cursor:    str
    has_more:  bool


# ── Field events (PM / downtime / exclusion) ─────────────────────────────────

class FieldEventCreate(BaseModel):
    id:             str
    project_id:     int
    kind:           str                      # pm | counts | excluded
    blocks:         str = ""
    date_from:      str
    date_to:        str
    hours:          float = 0
    exclusion_type: str = ""
    description:    str = ""
    created_at:     Optional[str] = None


class FieldEventOut(BaseModel):
    id:             str
    project_id:     int
    kind:           str
    blocks:         str
    date_from:      str
    date_to:        str
    hours:          float
    exclusion_type: str
    description:    str
    created_at:     str
    updated_at:     str

    model_config = {"from_attributes": True}


class FieldEventPullResponse(BaseModel):
    events:   List[FieldEventOut]
    cursor:   str
    has_more: bool


# ── Sync ──────────────────────────────────────────────────────────────────────

class SyncChange(BaseModel):
    entity:  str                     # "work_log" | "work_log_image"
    id:      str
    action:  str                     # "upsert" | "delete"
    version: int
    payload: dict[str, Any]


class SyncPushRequest(BaseModel):
    device_id:       str
    changes:         List[SyncChange]
    idempotency_key: Optional[str] = None   # UUID; enables safe retry without false conflicts


class SyncChangeResult(BaseModel):
    id:             str
    outcome:        str                  # "applied" | "conflict" | "skipped" | "error"
    server_version: Optional[int]  = None  # new version after apply
    server_row:     Optional[dict] = None  # full server row on conflict (for UI merge)
    message:        Optional[str]  = None


class SyncPushResponse(BaseModel):
    results: List[SyncChangeResult]


class SyncPullChange(BaseModel):
    entity:     str
    action:     str                  # "upsert" | "delete"
    id:         str
    data:       dict[str, Any]
    updated_at: str


class SyncPullResponse(BaseModel):
    changes:  List[SyncPullChange]
    cursor:   str                    # ISO datetime — pass as `since` on next call
    has_more: bool


# ── Image upload ──────────────────────────────────────────────────────────────

class ImageUploadResponse(BaseModel):
    id:             str
    work_log_id:    str
    filename:       str
    size_bytes:     int
    sha256:         str
    width:          Optional[int]
    height:         Optional[int]
    taken_at:       Optional[str]
    uploaded_at:    str
    download_url:   str
