"""tools/build_release.py — one command that produces the Windows installer.

    python tools\\build_release.py                full build (PyInstaller included)
    python tools\\build_release.py --skip-exe     re-make the installer from the
                                                  exe already in dist\\ (freezing
                                                  takes minutes; this is seconds)

Steps, in order:
  1. read APP_VERSION from services\\version.py and write installer\\version.iss
  2. pyinstaller --clean "BESS Tracker.spec"                 (unless --skip-exe)
  3. tools\\make_clean_db.py  -> build\\clean\\pv_bess_tracker.db
  4. check installer.iss ships nothing private  (see FORBIDDEN below)
  5. ISCC installer.iss  -> installer\\BESS_Tracker_Setup_<version>.exe

Step 4 exists because an earlier installer shipped the owner's live database,
which carried real customer data to whoever ran the setup. The check runs before
every compile and stops the build.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

ISS = os.path.join(ROOT, 'installer.iss')
VERSION_ISS = os.path.join(ROOT, 'installer', 'version.iss')
SPEC = os.path.join(ROOT, 'BESS Tracker.spec')
EXE = os.path.join(ROOT, 'dist', 'BESS Tracker.exe')
CLEAN_DB = os.path.join(ROOT, 'build', 'clean', 'pv_bess_tracker.db')
ISCC_KNOWN = r'C:\Program Files (x86)\Inno Setup 6\ISCC.exe'

# Text that must never appear in the .iss. The live database and the sync
# configuration (which holds login tokens) are the two files that must not
# leave this machine.
FORBIDDEN = (r'dist\pv_bess_tracker.db', 'sync_config.json')


# ── guard ────────────────────────────────────────────────────────────────────

def scan_iss(text: str) -> list:
    """Problems found in an .iss file's text. Empty list = safe to compile."""
    problems = []
    low = text.lower()
    for bad in FORBIDDEN:
        if bad.lower() in low:
            problems.append('references {} — it must never be packaged'.format(bad))
    if r'build\clean\pv_bess_tracker.db' not in low:
        problems.append(r'does not ship build\clean\pv_bess_tracker.db')
    if 'onlyifdoesntexist' not in low:
        problems.append('the database is not flagged onlyifdoesntexist — an '
                        'upgrade would overwrite existing data')
    return problems


def check_iss(path: str) -> None:
    with open(path, encoding='utf-8') as f:
        problems = scan_iss(f.read())
    if problems:
        print('REFUSING TO BUILD. {} :'.format(os.path.basename(path)))
        for p in problems:
            print('  - ' + p)
        raise SystemExit(2)
    print('[4/5] installer.iss checked: ships no private files')


# ── steps ────────────────────────────────────────────────────────────────────

def read_version() -> str:
    from services.version import APP_VERSION
    if not re.fullmatch(r'\d+(\.\d+){1,3}', APP_VERSION):
        raise SystemExit('APP_VERSION "{}" is not a dotted number; Inno Setup\'s '
                         'VersionInfoVersion cannot parse it'.format(APP_VERSION))
    return APP_VERSION


def write_version_iss(version: str) -> None:
    os.makedirs(os.path.dirname(VERSION_ISS), exist_ok=True)
    with open(VERSION_ISS, 'w', encoding='utf-8') as f:
        f.write('; Generated by tools\\build_release.py from services\\version.py.\n'
                '; Do not edit: bump APP_VERSION there instead.\n'
                '#define AppVersion "{}"\n'.format(version))
    print('[1/5] installer\\version.iss -> {}'.format(version))


def run(cmd: list, step: str) -> None:
    print('[{}] {}'.format(step, ' '.join(cmd)))
    sys.stdout.flush()
    rc = subprocess.call(cmd, cwd=ROOT)
    if rc != 0:
        raise SystemExit('{} failed with exit code {}'.format(cmd[0], rc))


def build_exe() -> None:
    run([sys.executable, '-m', 'PyInstaller', '--clean', SPEC], '2/5')
    if not os.path.isfile(EXE):
        raise SystemExit('PyInstaller finished but {} is missing'.format(EXE))


def build_clean_db() -> None:
    run([sys.executable, os.path.join(ROOT, 'tools', 'make_clean_db.py')], '3/5')
    if not os.path.isfile(CLEAN_DB):
        raise SystemExit('{} is missing'.format(CLEAN_DB))


def find_iscc() -> str:
    if os.path.isfile(ISCC_KNOWN):
        return ISCC_KNOWN
    from shutil import which
    found = which('ISCC.exe') or which('iscc')
    if found:
        return found
    raise SystemExit(
        'Inno Setup 6 not found. Expected it at:\n  {}\n'
        'Install it from https://jrsoftware.org/isdl.php (the Inno Setup\n'
        'Preprocessor component is required), or put ISCC.exe on PATH.'
        .format(ISCC_KNOWN))


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    skip_exe = '--skip-exe' in argv
    unknown = [a for a in argv if a not in ('--skip-exe',)]
    if unknown:
        print('unknown argument(s): {}\n{}'.format(' '.join(unknown), __doc__))
        return 2

    version = read_version()
    print('=== BESS Tracker {} ==='.format(version))
    write_version_iss(version)

    if skip_exe:
        if not os.path.isfile(EXE):
            raise SystemExit('--skip-exe, but there is no exe at {}'.format(EXE))
        print('[2/5] skipped (using the existing {})'.format(
            os.path.basename(EXE)))
    else:
        build_exe()

    build_clean_db()
    check_iss(ISS)
    run([find_iscc(), ISS], '5/5')

    out = os.path.join(ROOT, 'installer',
                       'BESS_Tracker_Setup_{}.exe'.format(version))
    if not os.path.isfile(out):
        raise SystemExit('ISCC reported success but {} is missing'.format(out))
    print('\nDONE  {}\n      {:.1f} MB'.format(
        out, os.path.getsize(out) / (1024.0 * 1024.0)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
